version: '3.5'

services:
  db:
    container_name: mimic3-db
    image: postgres:12
    shm_size: '4gb'
    env_file:
      - .env   
    volumes:    
      - './initialization/:/docker-entrypoint-initdb.d/' 
      - './db-data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - mimic-net
       
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - db
    logging:
      driver: none
    env_file:
      - .env
    networks:
      - mimic-net

networks:
  mimic-net:    
    name: mimic-net
    external: true

